import { Player } from '../interfaces/Player.ts';
import { Attribute } from '../interfaces/Attribute.ts';

export const GAME_USERS_MOCK: Player[] = 
[
  {
    _id: '66decc4ff42d4a193db77e11',
    name: 'Boss (BOT)',
    nickname: 'Boss (BOT)',
    avatar: 'https://lh3.googleusercontent.com/a/ACg8ocIs9M5Fz0Dg1M7KgxcDGVyUSOeCIrXQmEVToR9cipfo71RLlOE=s96-c',
    email: 'boss.bot@ikasle.aeg.eus',
    level: 18,
    role: 'acolyte',
    socketId: '',
    isBetrayer: true,
    profile: { name: 'Blasphemer' },
    attributes: {
      charisma: 129,
      constitution: 60,
      dexterity: 23,
      insanity: 95,
      intelligence: 29,
      strength: 18,
      resistance: 100,
      attack: -30,
      hit_points: 35,
      defense: 97,
      magic_resistance: 159,
      CFP: 95,
      BCFA: 113,
    },
    base_attributes: {
      charisma: 130,
      constitution: 60,
      dexterity: 23,
      insanity: 95,
      intelligence: 29,
      strength: 18,
      resistance: 100,
      attack: -30,
      hit_points: 35,
      defense: 97,
      magic_resistance: 159,
      CFP: 95,
      BCFA: 113,
    },
    equipment: {
      healing_potion: {
        modifiers: {
          hit_points: 40,
          intelligence: -5,
          dexterity: 0,
          constitution: 0,
          insanity: 0,
          charisma: 0,
          strength: 0,
        },
        _id: '668bca125319ea9afdff0754',
        name: 'Essence of Rejuvenation',
        description: 'This revitalizing potion restores energy and vitality to the drinker.',
        type: 'essence',
        image: '/images/equipment/potions/healing/healing_2.png',
        value: 10,
        min_lvl: 1,
      },
      antidote_potion: {
        _id: '668bca125319ea9afdff075e',
        name: 'Antidote of Frostbane Fever',
        description: 'A potent concoction brewed from the rare Lumina flowers that only bloom under the full moon...',
        type: 'antidote',
        image: '/images/equipment/potions/antidote/antidote_1.png',
        value: 10,
        recovery_effect: {
          modifiers: {
            hit_points: 0,
            intelligence: 0,
            dexterity: 0,
            insanity: 0,
            charisma: -8,
            constitution: -12,
            strength: 0,
          },
          _id: '6693fd5846527d0df5f0efe8',
          name: 'Frostbane Fever',
          description: 'A chilling illness that lowers the body temperature drastically, causing frost to form on the skin and organs to freeze.',
          type: 'illness',
          antidote_effects: ['restore_constitution', 'lesser_restore_charisma'],
          poison_effects: ['damage_constitution', 'lesser_damage_charisma'],
        },
        min_lvl: 1,
      },
      enhancer_potion: {
        modifiers: {
          intelligence: 0,
          dexterity: 0,
          constitution: 0,
          insanity: 20,
          charisma: 0,
          strength: 0,
        },
        _id: '668bca135319ea9afdff076b',
        name: 'Elixir of Madness',
        description:
          'A dangerous brew that plunges the drinker into a frenzy, this potion unleashes chaotic energy.',
        type: 'elixir',
        image: '/images/equipment/potions/enhancer/enhancer_2.png',
        value: 10,
        duration: 2,
        min_lvl: 1,
      },
      weapon: {
        modifiers: {
          intelligence: 0,
          dexterity: 0,
          constitution: 5,
          insanity: 30,
          charisma: 10,
          strength: 0,
        },
        _id: '67616050317c38e05431c530',
        name: 'Dagger of Venomous Promises',
        description: 'A poisoned blade that cuts through both flesh and trust.',
        type: 'weapon',
        image: '/images/betrayar/weapon.png',
        value: 60,
        base_percentage: 40,
        min_lvl: 2,
        die_faces: 100,
        die_modifier: 0,
        die_num: 1,
        isUnique: true,
        isActive: false,
      },
      helmet: {
        modifiers: {
          intelligence: 0,
          dexterity: 0,
          constitution: 5,
          insanity: 5,
          charisma: 10,
          strength: 0
        },
        _id: '67615f0d317c38e05431c527',
        name: 'Mask of Whispered Lies',
        description: 'Hides faces and words, sowing doubt among allies and foes alike.',
        type: 'helmet',
        image: '/images/betrayar/mask.png',
        value: 20,
        defense: 1,
        min_lvl: 1,
        isUnique: true,
        isActive: false
      },
      armor: {
        modifiers: {
          strength: 0,
          constitution: 10,
          dexterity: 0,
          intelligence: 0,
          insanity: 5,
          charisma: 10
        },
        _id: '67615e61317c38e05431c523',
        name: 'Blouse of Decaying Vows',
        description: 'Its rotted seams still carry the weight of broken oaths and betrayed promises.',
        type: 'armor',
        image: '/images/betrayar/blouse.png',
        value: 50,
        defense: 1,
        isUnique: true,
        isActive: false,
        min_lvl: 1
      },
      shield: {
        modifiers: {
          intelligence: 0,
          dexterity: 0,
          constitution: 5,
          insanity: 5,
          charisma: 10,
          strength: 0
        },
        _id: '67615f8d317c38e05431c52b',
        name: 'Shield of Forsaken Oaths',
        description: 'Guards the bearer with the strength of shattered pacts and forgotten loyalties.',
        type: 'shield',
        image: '/images/betrayar/shield.png',
        value: 15,
        defense: 1,
        min_lvl: 1,
        isUnique: true,
        isActive: false
      },
      boot: {
        modifiers: {
          intelligence: 0,
          dexterity: 0,
          constitution: 5,
          insanity: 5,
          charisma: 10,
          strength: 0
        },
        _id: '676160cd317c38e05431c534',
        name: 'Boots of Silent Betrayal',
        description: 'Leave invisible tracks in the mire of disloyalty and deceit.',
        type: 'boot',
        image: '/images/betrayar/boot.png',
        value: 20,
        defense: 1,
        min_lvl: 1,
        isActive: false,
        isUnique: true
      },
    },
    inventory: { healing_potions: [], antidote_potions: [], enhancer_potions: [] },
    status: { ethaziumCurse: false, common_diseases: [], tired: false },
    isAlive: true
  },
  {
    _id: '66decc4ff42d4a193db77e71',
    name: 'AITOR MENDIBURU BOTAS',
    nickname: 'Dr Github',
    avatar: 'https://lh3.googleusercontent.com/a/ACg8ocIs9M5Fz0Dg1M7KgxcDGVyUSOeCIrXQmEVToR9cipfo71RLlOE=s96-c',
    email: 'aitor.mendiburu@ikasle.aeg.eus',
    level: 18,
    role: 'acolyte',
    socketId: '3o0LeOf-R28YvEMhAAAB',
    isBetrayer: true,
    profile: { name: 'Blasphemer' },
    attributes: {
      charisma: 130,
      constitution: 60,
      dexterity: 50,
      insanity: 95,
      intelligence: 29,
      strength: 18,
      resistance: 100,
      attack: -30,
      hit_points: 35,
      defense: 97,
      magic_resistance: 159,
      CFP: 95,
      BCFA: 113,
    },
    base_attributes: {
      charisma: 130,
      constitution: 60,
      dexterity: 23,
      insanity: 95,
      intelligence: 29,
      strength: 18,
      resistance: 100,
      attack: -30,
      hit_points: 35,
      defense: 97,
      magic_resistance: 159,
      CFP: 95,
      BCFA: 113,
    },
    equipment: {
      healing_potion: {
        modifiers: {
          hit_points: 40,
          intelligence: -5,
          dexterity: 0,
          constitution: 0,
          insanity: 0,
          charisma: 0,
          strength: 0,
        },
        _id: '668bca125319ea9afdff0754',
        name: 'Essence of Rejuvenation',
        description: 'This revitalizing potion restores energy and vitality to the drinker.',
        type: 'essence',
        image: '/images/equipment/potions/healing/healing_2.png',
        value: 10,
        min_lvl: 1,
      },
      antidote_potion: {
        _id: '668bca125319ea9afdff075e',
        name: 'Antidote of Frostbane Fever',
        description: 'A potent concoction brewed from the rare Lumina flowers that only bloom under the full moon...',
        type: 'antidote',
        image: '/images/equipment/potions/antidote/antidote_1.png',
        value: 10,
        recovery_effect: {
          modifiers: {
            hit_points: 0,
            intelligence: 0,
            dexterity: 0,
            insanity: 0,
            charisma: -8,
            constitution: -12,
            strength: 0,
          },
          _id: '6693fd5846527d0df5f0efe8',
          name: 'Frostbane Fever',
          description: 'A chilling illness that lowers the body temperature drastically, causing frost to form on the skin and organs to freeze.',
          type: 'illness',
          antidote_effects: ['restore_constitution', 'lesser_restore_charisma'],
          poison_effects: ['damage_constitution', 'lesser_damage_charisma'],
        },
        min_lvl: 1,
      },
      enhancer_potion: {
        modifiers: {
          intelligence: 0,
          dexterity: 0,
          constitution: 0,
          insanity: 20,
          charisma: 0,
          strength: 0,
        },
        _id: '668bca135319ea9afdff076b',
        name: 'Elixir of Madness',
        description:
          'A dangerous brew that plunges the drinker into a frenzy, this potion unleashes chaotic energy.',
        type: 'elixir',
        image: '/images/equipment/potions/enhancer/enhancer_2.png',
        value: 10,
        duration: 2,
        min_lvl: 1,
      },
      weapon: {
        modifiers: {
          intelligence: 0,
          dexterity: 0,
          constitution: 5,
          insanity: 30,
          charisma: 10,
          strength: 0,
        },
        _id: '67616050317c38e05431c530',
        name: 'Dagger of Venomous Promises',
        description: 'A poisoned blade that cuts through both flesh and trust.',
        type: 'weapon',
        image: '/images/betrayar/weapon.png',
        value: 60,
        base_percentage: 40,
        min_lvl: 2,
        die_faces: 100,
        die_modifier: 0,
        die_num: 1,
        isUnique: true,
        isActive: false,
      },
      helmet: {
        modifiers: {
          intelligence: 0,
          dexterity: 0,
          constitution: 5,
          insanity: 5,
          charisma: 10,
          strength: 0
        },
        _id: '67615f0d317c38e05431c527',
        name: 'Mask of Whispered Lies',
        description: 'Hides faces and words, sowing doubt among allies and foes alike.',
        type: 'helmet',
        image: '/images/betrayar/mask.png',
        value: 20,
        defense: 1,
        min_lvl: 1,
        isUnique: true,
        isActive: false
      },
      armor: {
        modifiers: {
          strength: 0,
          constitution: 10,
          dexterity: 0,
          intelligence: 0,
          insanity: 5,
          charisma: 10
        },
        _id: '67615e61317c38e05431c523',
        name: 'Blouse of Decaying Vows',
        description: 'Its rotted seams still carry the weight of broken oaths and betrayed promises.',
        type: 'armor',
        image: '/images/betrayar/blouse.png',
        value: 50,
        defense: 1,
        isUnique: true,
        isActive: false,
        min_lvl: 1
      },
      shield: {
        modifiers: {
          intelligence: 0,
          dexterity: 0,
          constitution: 5,
          insanity: 5,
          charisma: 10,
          strength: 0
        },
        _id: '67615f8d317c38e05431c52b',
        name: 'Shield of Forsaken Oaths',
        description: 'Guards the bearer with the strength of shattered pacts and forgotten loyalties.',
        type: 'shield',
        image: '/images/betrayar/shield.png',
        value: 15,
        defense: 1,
        min_lvl: 1,
        isUnique: true,
        isActive: false
      },
      boot: {
        modifiers: {
          intelligence: 0,
          dexterity: 0,
          constitution: 5,
          insanity: 5,
          charisma: 10,
          strength: 0
        },
        _id: '676160cd317c38e05431c534',
        name: 'Boots of Silent Betrayal',
        description: 'Leave invisible tracks in the mire of disloyalty and deceit.',
        type: 'boot',
        image: '/images/betrayar/boot.png',
        value: 20,
        defense: 1,
        min_lvl: 1,
        isActive: false,
        isUnique: true
      },
    },
    inventory: { healing_potions: [], antidote_potions: [], enhancer_potions: [] },
    status: { ethaziumCurse: false, common_diseases: [], tired: false },
    isAlive: true
  },
  {
    _id: '66dec6ab4c27dff822d80066',
    name: 'ENEKO LARREA PEREZ',
    nickname: '六四事件1989',
    avatar: 'https://lh3.googleusercontent.com/a-/ALV-UjW79byZC_JXJCJrG0AsR_UyQdUoLxTi5YQ5W-4oD4UbHC1NI3Mo',
    email: 'eneko.larrea@ikasle.aeg.eus',
    level: 18,
    role: 'acolyte',
    socketId: 'xmfysZuwGKGtsc0IAAAD',
    isBetrayer: false,
    profile: { name: 'Gossiper' },
    attributes: {
      charisma: 99,
      constitution: 53,
      dexterity: 81,
      insanity: 34,
      intelligence: 107,
      strength: 30,
      resistance: 100,
      attack: 13,
      hit_points: 117,
      defense: 187,
      magic_resistance: 206,
      CFP: 34,
      BCFA: 64,
    },
    base_attributes: {
      charisma: 99,
      constitution: 53,
      dexterity: 81,
      insanity: 34,
      intelligence: 107,
      strength: 30,
      resistance: 100,
      attack: 13,
      hit_points: 117,
      defense: 187,
      magic_resistance: 206,
      CFP: 34,
      BCFA: 64,
    },
    equipment: {
      healing_potion: {
        modifiers: {
          hit_points: 20,
          intelligence: 0,
          dexterity: 0,
          constitution: 0,
          insanity: 0,
          charisma: 0,
          strength: 0,
        },
        _id: '668bca125319ea9afdff0750',
        name: 'Essence of Vitality',
        description: 'A rejuvenating potion that restores vigor and vitality to the drinker.',
        type: 'essence',
        image: '/images/equipment/potions/healing/healing_1.png',
        value: 10,
        min_lvl: 1,
      },
      antidote_potion: {
        _id: '668bca125319ea9afdff0764',
        name: 'Antidote of Wailing Plague',
        description:
          'A cooling elixir brewed from the leaves of the Frostmind plant, alleviating migraines and clearing hallucinations.',
        type: 'antidote',
        image: '/images/equipment/potions/antidote/antidote_3.png',
        value: 10,
        recovery_effect: {
          modifiers: {
            hit_points: 0,
            intelligence: 0,
            dexterity: 0,
            insanity: 7,
            charisma: -9,
            constitution: 0,
            strength: 0,
          },
          _id: '6693fd5846527d0df5f0efe9',
          name: 'Wailing Plague',
          description:
            'An infectious disease that causes the afflicted to uncontrollably wail in pain, spreading misery and despair.',
          type: 'illness',
          antidote_effects: ['lesser_restore_insanity', 'lesser_restore_charisma'],
          poison_effects: ['lesser_damage_insanity', 'lesser_damage_charisma'],
        },
        min_lvl: 1,
      },
      enhancer_potion: {
        modifiers: {
          intelligence: 0,
          dexterity: 0,
          constitution: 0,
          insanity: 20,
          charisma: 0,
          strength: 0,
        },
        _id: '668bca135319ea9afdff076b',
        name: 'Elixir of Madness',
        description:
          'A dangerous brew that plunges the drinker into a frenzy, this potion unleashes chaotic energy.',
        type: 'elixir',
        image: '/images/equipment/potions/enhancer/enhancer_2.png',
        value: 10,
        duration: 2,
        min_lvl: 1,
      },
      weapon: {
        modifiers: {
          intelligence: 0,
          dexterity: 0,
          constitution: 5,
          insanity: 30,
          charisma: 10,
          strength: 0,
        },
        _id: '67616050317c38e05431c530',
        name: 'Dagger of Venomous Promises',
        description: 'A poisoned blade that cuts through both flesh and trust.',
        type: 'weapon',
        image: '/images/betrayar/weapon.png',
        value: 60,
        base_percentage: 40,
        min_lvl: 2,
        die_faces: 100,
        die_modifier: 0,
        die_num: 1,
        isUnique: true,
        isActive: false,
      },
      armor: {
        modifiers: {
          strength: -9,
          constitution: 0,
          dexterity: 30,
          intelligence: 15,
          insanity: 0,
          charisma: 25
        },
        _id: '66f3e0f7b32d7add9a087690',
        name: 'Valkyrie\'s Armor',
        description: 'Worn by legendary warriors, this armor is said to protect those worthy.',
        type: 'armor',
        image: '/images/equipment/armors/heavy_armor_27.png',
        value: 1030,
        defense: 88,
        isUnique: false,
        isActive: true,
        min_lvl: 16
      },
      helmet: {
        modifiers: {
          intelligence: 8,
          dexterity: 5,
          constitution: 10,
          insanity: 4,
          charisma: 6,
          strength: 7
        },
        _id: '66fa4a4385f0d4f8e349da7e',
        name: 'Eternal Guardian Visor',
        description: 'Forged in the fires of valor.',
        type: 'helmet',
        image: '/images/equipment/helmets/helmet_31.png',
        value: 1200,
        defense: 35,
        min_lvl: 12,
        isUnique: true,
        isActive: false
      },
      boot: {
        modifiers: {
          intelligence: 2,
          dexterity: 3,
          constitution: 10,
          insanity: 5,
          charisma: 4,
          strength: 6
        },
        _id: '66f694d84a8f1157dab87bc3',
        name: 'Berserker\'s Fury Boots',
        description: 'Fuel your rage and strength.',
        type: 'boot',
        image: '/images/equipment/boots/boot_11.png',
        value: 400,
        defense: 36,
        min_lvl: 15,
        isActive: true,
        isUnique: false
      },
      shield: {
        modifiers: {
          intelligence: 3,
          dexterity: 3,
          constitution: 10,
          insanity: 0,
          charisma: 0,
          strength: 11
        },
        _id: '66f27c81c114335cadf45d88',
        name: 'Reinforced Steel Shield',
        description: 'A heavily reinforced steel shield.',
        type: 'shield',
        image: '/images/equipment/shields/shield_25.png',
        value: 42,
        defense: 23,
        min_lvl: 5,
        isUnique: false,
        isActive: true
      },
    },
    inventory: { healing_potions: [], antidote_potions: [], enhancer_potions: [] },
    status: { ethaziumCurse: false, common_diseases: [], tired: false },
    isAlive: true
  },
];

export const playerMock: Player = 
{
  _id: '66decc4ff42d4a193db77e71',
  name: 'AITOR MENDIBURU BOTAS',
  nickname: 'Dr Github',
  avatar: 'https://lh3.googleusercontent.com/a/ACg8ocIs9M5Fz0Dg1M7KgxcDGVyUSOeCIrXQmEVToR9cipfo71RLlOE=s96-c',
  email: 'aitor.mendiburu@ikasle.aeg.eus',
  level: 18,
  role: 'acolyte',
  socketId: '3o0LeOf-R28YvEMhAAAB',
  isBetrayer: true,
  profile: { name: 'Blasphemer' },
  attributes: {
    charisma: 130,
    constitution: 60,
    dexterity: 23,
    insanity: 95,
    intelligence: 29,
    strength: 18,
    resistance: 100,
    attack: -30,
    hit_points: 35,
    defense: 97,
    magic_resistance: 159,
    CFP: 95,
    BCFA: 113,
  },
  base_attributes: {
    charisma: 130,
    constitution: 60,
    dexterity: 23,
    insanity: 95,
    intelligence: 29,
    strength: 18,
    resistance: 100,
    attack: -30,
    hit_points: 35,
    defense: 97,
    magic_resistance: 159,
    CFP: 95,
    BCFA: 113,
  },
  equipment: {
    healing_potion: {
      modifiers: {
        hit_points: 40,
        intelligence: -5,
        dexterity: 0,
        constitution: 0,
        insanity: 0,
        charisma: 0,
        strength: 0,
      },
      _id: '668bca125319ea9afdff0754',
      name: 'Essence of Rejuvenation',
      description: 'This revitalizing potion restores energy and vitality to the drinker.',
      type: 'essence',
      image: '/images/equipment/potions/healing/healing_2.png',
      value: 10,
      min_lvl: 1,
    },
    antidote_potion: {
      _id: '668bca125319ea9afdff075e',
      name: 'Antidote of Frostbane Fever',
      description: 'A potent concoction brewed from the rare Lumina flowers that only bloom under the full moon...',
      type: 'antidote',
      image: '/images/equipment/potions/antidote/antidote_1.png',
      value: 10,
      recovery_effect: {
        modifiers: {
          hit_points: 0,
          intelligence: 0,
          dexterity: 0,
          insanity: 0,
          charisma: -8,
          constitution: -12,
          strength: 0,
        },
        _id: '6693fd5846527d0df5f0efe8',
        name: 'Frostbane Fever',
        description: 'A chilling illness that lowers the body temperature drastically, causing frost to form on the skin and organs to freeze.',
        type: 'illness',
        antidote_effects: ['restore_constitution', 'lesser_restore_charisma'],
        poison_effects: ['damage_constitution', 'lesser_damage_charisma'],
      },
      min_lvl: 1,
    },
    enhancer_potion: {
      modifiers: {
        intelligence: 0,
        dexterity: 0,
        constitution: 0,
        insanity: 20,
        charisma: 0,
        strength: 0,
      },
      _id: '668bca135319ea9afdff076b',
      name: 'Elixir of Madness',
      description:
        'A dangerous brew that plunges the drinker into a frenzy, this potion unleashes chaotic energy.',
      type: 'elixir',
      image: '/images/equipment/potions/enhancer/enhancer_2.png',
      value: 10,
      duration: 2,
      min_lvl: 1,
    },
    weapon: {
      modifiers: {
        intelligence: 0,
        dexterity: 0,
        constitution: 5,
        insanity: 30,
        charisma: 10,
        strength: 0,
      },
      _id: '67616050317c38e05431c530',
      name: 'Dagger of Venomous Promises',
      description: 'A poisoned blade that cuts through both flesh and trust.',
      type: 'weapon',
      image: '/images/betrayar/weapon.png',
      value: 60,
      base_percentage: 40,
      min_lvl: 2,
      die_faces: 100,
      die_modifier: 0,
      die_num: 1,
      isUnique: true,
      isActive: false,
    },
    helmet: {
      modifiers: {
        intelligence: 0,
        dexterity: 0,
        constitution: 5,
        insanity: 5,
        charisma: 10,
        strength: 0
      },
      _id: '67615f0d317c38e05431c527',
      name: 'Mask of Whispered Lies',
      description: 'Hides faces and words, sowing doubt among allies and foes alike.',
      type: 'helmet',
      image: '/images/betrayar/mask.png',
      value: 20,
      defense: 1,
      min_lvl: 1,
      isUnique: true,
      isActive: false
    },
    armor: {
      modifiers: {
        strength: 0,
        constitution: 10,
        dexterity: 0,
        intelligence: 0,
        insanity: 5,
        charisma: 10
      },
      _id: '67615e61317c38e05431c523',
      name: 'Blouse of Decaying Vows',
      description: 'Its rotted seams still carry the weight of broken oaths and betrayed promises.',
      type: 'armor',
      image: '/images/betrayar/blouse.png',
      value: 50,
      defense: 1,
      isUnique: true,
      isActive: false,
      min_lvl: 1
    },
    shield: {
      modifiers: {
        intelligence: 0,
        dexterity: 0,
        constitution: 5,
        insanity: 5,
        charisma: 10,
        strength: 0
      },
      _id: '67615f8d317c38e05431c52b',
      name: 'Shield of Forsaken Oaths',
      description: 'Guards the bearer with the strength of shattered pacts and forgotten loyalties.',
      type: 'shield',
      image: '/images/betrayar/shield.png',
      value: 15,
      defense: 1,
      min_lvl: 1,
      isUnique: true,
      isActive: false
    },
    boot: {
      modifiers: {
        intelligence: 0,
        dexterity: 0,
        constitution: 5,
        insanity: 5,
        charisma: 10,
        strength: 0
      },
      _id: '676160cd317c38e05431c534',
      name: 'Boots of Silent Betrayal',
      description: 'Leave invisible tracks in the mire of disloyalty and deceit.',
      type: 'boot',
      image: '/images/betrayar/boot.png',
      value: 20,
      defense: 1,
      min_lvl: 1,
      isActive: false,
      isUnique: true
    },
  },
  inventory: { healing_potions: [], antidote_potions: [], enhancer_potions: [] },
  status: { ethaziumCurse: false, common_diseases: [], tired: false },
  isAlive: true
};

export const attributesMock: Attribute = 
{
  charisma: 130,
  constitution: 60,
  dexterity: 23,
  insanity: 95,
  intelligence: 29,
  strength: 18,
  resistance: 100,
  attack: -30,
  hit_points: 35,
  defense: 97,
  magic_resistance: 159,
  CFP: 95,
  BCFA: 113,
};
