name: Deploy Kaotika Battle Server

on:
  push:
    branches:
      - main  

jobs:
  build:
    runs-on: self-hosted 

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Restaurar archivo .env
      run: cp ~/server-actions-runner/.env $GITHUB_WORKSPACE/.env
    - name: Configuration
      run: |
        echo "Configuring Enviroment..."

    - name: Pull changes from repo
      run: |
          git pull origin main
        
    - name: Installing dependencies
      run: |
        npm install

    - name: Build application
      run: |
        npm run build

    - name: Deploy application on pm2
      run: |
        pm2 stop kaotika-battle-server || true
        pm2 restart kaotika-battle-server

    - name: Clean after deploy
      run: |
        pm2 save
        echo "Deploy complete"
