name: Deploy Kaotika Battle Server (Docker)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create .env file from GitHub secret
        run: echo "${{ secrets.MOBILE_ENV_FILE }}" > .env

      - name: Pull latest changes
        run: git pull origin main

      - name: Build and restart Docker container
        run: |
          cd $GITHUB_WORKSPACE
          if [ $(docker ps -aq -f name=$CONTAINER_NAME) ]; then
            docker rm -f $CONTAINER_NAME
          fi
          docker compose -f docker-compose.yml build server
          docker compose -f docker-compose.yml up -d server

      - name: Clean up
        run: echo "Deployment complete."
