name: Deploy Kaotika Battle Server

on:
  push:
    branches:
      - main  

jobs:
  build:
    runs-on: self-hosted 

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Configuration
      run: |
        echo "Configuring Enviroment..."

    - name: Verify cloned repo
      run: |
        if [ -d "$GITHUB_WORKSPACE/.git" ]; then
          echo "Repository exists, updating..."
          cd $GITHUB_WORKSPACE
          git pull origin main
        else
          echo "Repository not found, cloning..."
          git clone git@github.com:legends-of-kaotika/kaotika-battle-server.git
        fi

    - name: Installing dependencies
      run: |
        cd $GITHUB_WORKSPACE
        npm install

    - name: Build application
      run: |
        cd $GITHUB_WORKSPACE
        npm run build

    - name: Deploy application on pm2
      run: |
        pm2 stop kaotika-battle-server || true
        pm2 restart kaotika-battle-server

    - name: Clean after deploy
      run: |
        pm2 save
        echo "Deploy complete"
