name: PM2 Update
on:
  push:
    branches:
      - main
      - KBS-50

jobs:
  pm2-update:
    name: Update PM2 Server
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Get latest changes
        run: |
          cd "/home/daw1/Documentos/KBS/kaotika-battle-server" &&
          git config pull.rebase false &&
          git pull origin KBS-50

      - name: Install dependencies
        run: |
          cd "/home/daw1/Documentos/KBS/kaotika-battle-server" &&
          npm install

      - name: Restart PM2
        run: |
          cd "/home/daw1/Documentos/KBS/kaotika-battle-server" &&
          pm2 reload ecosystem.config.js --watch -i max